[package]
name = "simple-enc-dec"
version = "0.1.0"
edition = "2024"

[dependencies]
openssl = "0.10"
base64 = "0.22"
ipc-broker = "1.0"
tokio = "1"
anyhow = "1.0.100"
serde_json = "1.0.145"
serde = "1.0.228"
async-trait = "0.1.89"
