name: Rust CI (Windows)

on:
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenSSL
        shell: pwsh
        run: |
          choco install openssl --params "/InstallDir:C:\Program Files" --no-progress -y 
          dir "C:\Program Files\OpenSSL\lib\VC"
          dir "C:\Program Files\OpenSSL\lib\VC\x64"
          echo "OPENSSL_DIR=C:\Program Files\OpenSSL" >> $env:GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=C:\Program Files\OpenSSL\include" >> $env:GITHUB_ENV
          echo "OPENSSL_LIB_DIR=C:\Program Files\OpenSSL\lib\VC\x64\MT" >> $env:GITHUB_ENV

      - run: cargo fmt --all -- --check
      - run: cargo clippy -- --deny warnings
      - run: cargo build --verbose
      - run: cargo test --verbose